### ISSUE TITLE
Add Express routes: REST for Application (later Contact)

### ISSUE THREAD

**Issue by daniel-sarran** [kevinsekuj/cs467-capstone#10]
Application:

MVP is only ReadAll, Create...

Otherwise:
- Create
- Read
- ReadAll
- Update*
- Delete*

Note that for update & delete I'd like the option to pass in multiple IDs, if possible
e.g. check multiple rows and delete them all
e.g. check multiple rows, and bulk update status to rejected

Contact:
- Create
- Read
- Update
- Delete

Skills:
- Create
- Read
- Update
- Delete

**Comment by rngolam** [comment]
done
