### ISSUE TITLE
React component hierarchy bug

### ISSUE THREAD

**Issue by kevinsekuj** [kevinsekuj/cs467-capstone#38]
![image](https://user-images.githubusercontent.com/68984611/198931472-642f2d17-8931-48a7-8ac8-71d0016dd565.png)

**Comment by daniel-sarran** [comment]
Hmmmmmm was this from my PR... I didnt touch buttons :jettmad:
k thx

**Comment by daniel-sarran** [comment]
I think this
![image](https://user-images.githubusercontent.com/53810232/198932059-da5eb43c-9fd1-4cf4-a3e7-be3c56d1eba8.png)

IconButton -> Box -> LogoutButton/LoginButton

**Comment by kevinsekuj** [comment]
fixed
